name: club_backend
description: A Dart backend for managing clubs.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  mysql1: ^0.20.0
  dotenv: ^4.2.0
  mime: ^1.0.4
  shelf_multipart: ^1.0.0
  shelf_static: ^1.1.1
  pool: ^1.5.0
