services:
  - type: web
    name: club-backend
    env: docker
    plan: free
    buildCommand: dart pub get
    startCommand: dart run bin/main.dart
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: your-user
      - key: DB_PASSWORD
        value: your-password
      - key: DB_NAME
        value: your-db-name
